# Configuration options for your blog - customise to taste
# This file contains no secret information, so can be stored in source control (unlike database.yml)
title: So Many Robots!
url:   http://www.somanyrobots.com
exception_notifications: somers.ben@gmail.com

# Delete the following section if your site will not be acting as an OpenID delegate (http://wiki.openid.net/Delegation)
# If you're deploying with mongrel, make sure you read http://rhnh.net/2008/04/13/nginx-openid-delegation-and-yadis
open_id_delegation:
  server:   http://www.myopenid.com/server
  delegate: http://somanyrobots.myopenid.com

